# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Ben Solomon
email: bds1217@gmail.com
author: Ben Solomon
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2015 Ben Solomon. All Rights Reserved.'
credits: 'Credits: Site theme adapted from "Landing Page," created by <a href="http://startbootstrap.com/">Start Bootstrap</a>
          and modified for Jekyll by <a href="https://github.com/swcool">Shane Weng</a>.</p> '

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/BenSolomon/
  - title: researchgate
    url: https://www.researchgate.net/profile/Benjamin_Solomon
  - title: flickr
    url: https://www.flickr.com/photos/bds46/
